name: Deploy Laravel + Node.js via SFTP

on:
  push:
    branches:
      - main  # Verander dit naar je productiebranch indien nodig

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Haal de laatste versie van de repo op
      - name: Haal de laatste versie op
        uses: actions/checkout@v3

      # 2️⃣ Installeer Node.js en bouw assets
      - name: Installeer Node.js en NPM pakketten
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Pas aan indien een andere versie nodig is

      - name: Installeer en build frontend assets
        run: |
          npm install
          npm run build  # Zorg dat deze script correct is ingesteld in package.json

      # 3️⃣ Installeer PHP en Composer dependencies
      - name: Installeer PHP en Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Pas aan indien een andere versie nodig is
          tools: composer
          extensions: mbstring, exif, pcntl, bcmath, gd

      - name: Installeer Composer dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /var/www/html/lara.safouh.nl/


      # 4️⃣ Upload bestanden via SFTP (of FTP, zie onderaan)
      # - name: Deploy via SFTP
      #   uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      #   with:
      #     username: ${{ secrets.SFTP_USERNAME }}
      #     server: ${{ secrets.SFTP_SERVER }}
      #     port: ${{ secrets.SFTP_PORT }}
      #     password: ${{ secrets.SFTP_PASSWORD }}
      #     remote_path: /var/www/html/yourproject/  # Pas dit aan naar jouw serverpad
      #     local_path: ./  # Upload alle bestanden
      #     args: "-o ConnectTimeout=5"

      # # 5️⃣ Voer Laravel-optimalisaties uit op de server (optioneel, vereist SSH)
      # - name: Voer Artisan-commando's uit (optioneel)
      #   run: |
      #     ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
      #       cd /var/www/html/yourproject
      #       php artisan migrate --force
      #       php artisan config:cache
      #       php artisan route:cache
      #       php artisan view:cache
      #     EOF
      #   if: success()


      # - name: Deploy via FTP
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      #   with:
      #     server: ${{ secrets.FTP_SERVER }}
      #     username: ${{ secrets.FTP_USERNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     local-dir: ./
      #     server-dir: /var/www/html/yourproject/
